### ISSUE TITLE
抖音解析获取新的地址失败

### ISSUE THREAD

**Issue by guilairengshishaonian** [zhangwenkang0/remove-water-mark-server#1]
![image](https://github.com/zhangwenkang0/remove-water-mark-server/assets/49903984/8615d2ab-6714-40c7-8a22-029cf94f3ce2)
![image](https://github.com/zhangwenkang0/remove-water-mark-server/assets/49903984/3afed601-bd02-4a94-99c2-c3d4ffaef809)
请教下这块502是什么问题

**Comment by zhangwenkang0** [comment]
按这个看来是，获取抖音视频的地址改了，这个服务不可用了。需要重新解析下找到获取视频的url

**Comment by guilairengshishaonian** [comment]
对 https://tiktok.iculture.cc/X-Bogus 这个地址的问题
我刚给你打上备注v了 可以加下么
